#!/bin/bash
# 最新webコンテンツをGitHubからコンテナへ取り込む

# コンテンツ元の環境変数がなければエラー終了
if [ -z $CONTENTS_SOURCE_URL ]; then
    exit 1
fi

# 初回はGitHubからコンテンツをクローン
git clone $CONTENTS_SOURCE_URL /data

# ２回目以降は1分ごとに変更差分を取得する
cd /data
while ture
do
    data
    sleep 60
    git pull
done